In [1]:
import pandas as pd
import lux

In [4]:
df = pd.read_json("test.json")
df

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,-5,=,IF,(,A1,,>,,0,",",...,SUM,(,A1,",",,B1,),=,C1,+
1,-4,=,IF,(,A2,,>,,0,",",...,SUM,(,A2,",",,B2,),=,C2,+
2,-3,=,IF,(,A3,,>,,0,",",...,SUM,(,A3,",",,B3,),=,C3,+
3,-2,=,IF,(,A4,,>,,0,",",...,SUM,(,A4,",",,B4,),=,C4,+
4,-1,=,IF,(,A5,,>,,0,",",...,SUM,(,A5,",",,B5,),=,C5,+
5,0,=,IF,(,A6,,>,,0,",",...,SUM,(,A6,",",,B6,),=,C6,+
6,1,=,IF,(,A7,,>,,0,",",...,SUM,(,A7,",",,B7,),=,C7,+
7,2,=,IF,(,A8,,>,,0,",",...,SUM,(,A8,",",,B8,),=,C8,+
8,3,=,IF,(,A9,,>,,0,",",...,SUM,(,A9,",",,B9,),=,C9,+
9,4,=,IF,(,A10,,>,,0,",",...,SUM,(,A10,",",,B10,),=,C10,+
10,5,=,IF,(,A11,,>,,0,",",...,SUM,(,A11,",",,B11,),=,C11,+
11,6,=,IF,(,A12,,>,,0,",",...,SUM,(,A12,",",,B12,),=,C12,+
12,7,=,IF,(,A13,,>,,0,",",...,SUM,(,A13,",",,B13,),=,C13,+
13,8,=,IF,(,A14,,>,,0,",",...,SUM,(,A14,",",,B14,),=,C14,+
14,9,=,IF,(,A15,,>,,0,",",...,SUM,(,A15,",",,B15,),=,C15,+